config/routes.rb
MedPort::Application.routes.draw do
  get "organizations/show"

    root :to => "pages#home"

    devise_for :users

    resources :users, :only => [ :show, :index ]
    resources :categories
    resources :healthcats, :path => "sprav/cats"  do
        resources :healthcats, :path => "/subcats", :as => :subcats do
            resources :articles, :only => [ :show, :index ]
        end
    end
    resources :articles
    resources :bodyparts
    resources :tags
    resources :organizations

    match "home" => "pages#home", :as => "home"
    match "parallax" => "pages#parallax", :as => "parallax" #remove (test parallax scrolling)
    match "sprav/articles" => "articles#health", :as => "health_articles"

    namespace :admin do
        match "home" => "pages#home", :as => "home"
        match "canvas" => "pages#canvas", :as => "canvas" #remove this path (canvas test page)

        resources :healthcats, :path => "zabolevaniya/categories" do
            collection do
                delete 'destroy'
                post 'move'
            end
        end
        resources :bodyparts do
            collection do
                delete 'destroy'
            end
        end
        resources :articles do
            collection do
                delete 'destroy'
            end
        end
        resources :tags do
            collection do
                delete 'destroy'
            end
        end
        resources :organizations do
            collection do
                delete 'destroy'
            end
        end
    end
end

app/models/healthcat.rb
class Healthcat < ActiveRecord::Base
    include Translator

    attr_accessible :name, :translated_name, :description, :parent_id, :gender, :bodypart_names

    cattr_accessor :genders do
        [ [ I18n.t('shared.genders.male'), "male" ], [ I18n.t('shared.genders.female'), "female" ] ]
    end

    has_many :subcats, :class_name => "Healthcat", :foreign_key => "parent_id"
    belongs_to :parent, :class_name => "Healthcat", :foreign_key => "parent_id"
    has_many :placings, :dependent => :destroy
    has_many :bodyparts, :through => :placings
    has_many :articles, :as => :categorizable

    scope :all_parents, lambda { where('parent_id IS ?', nil).order(:name) }

    validates_presence_of :name

    def count_of_articles
        count = 0
        if not self.subcats.blank?
            self.subcats.each do |child|
                count = count + child.articles.count if not child.articles.blank?
            end
        else
            count = self.articles.count if not self.articles.blank?
        end
        return count
    end

    def to_param
        "#{id}-#{translated_name}"
    end

    def bodypart_names=(names)
        names_line = "".encode("cp1251") + names
        names_line = names_line.gsub(/^(, *)+/, "")
        self.bodyparts = Bodypart.with_names(names_line.split(%r{, +}))
    end

    def bodypart_names
        bodyparts.map(&:name).join(', ')
    end

    before_save :set_childs_gender, :set_translate_name

    private
        def set_childs_gender
            self.gender = self.parent.gender if not self.parent_id.blank?
        end

        def set_translate_name
            self.translated_name = translate(self.name)
        end
end

app/controllers/admin/healthcats_controller.rb
class Admin::HealthcatsController < ApplicationController
    before_filter :check_authorized
    before_filter :find_healthcat, :only => [ :edit, :update, :show ]
    before_filter :bodyparts_list, :only => [ :edit, :update, :new, :create ]

    load_and_authorize_resource

    layout "dashboard"

    def index
        @healthcats = Healthcat.all_parents.page(params[:page]).per(50)
    end

    def new
        @healthcat = Healthcat.new
    end

    def create
        @healthcat = Healthcat.new(params[:healthcat])
        if params[:cancel_button] || @healthcat.save
            redirect_to admin_healthcats_path
        else
            render :new
        end
    end

    def edit
    end

    def update
        if params[:cancel_button] || @healthcat.update_attributes(params[:healthcat])
            redirect_to :controller => 'admin/healthcats', :action => 'index'
        else
            render :edit
        end
    end

    def show
        @children = @healthcat.subcats
    end

    def destroy
        Healthcat.find(params[:cats]).each do |cat|
            if not cat.subcats.blank?
                cat.subcats.each do |child|
                    Healthcat.find(child.id).destroy
                end
            end
            cat.destroy
        end
        redirect_to admin_healthcats_path
    end

    def move
        if params[:delete_button]
            Healthcat.find(params[:cats]).each do |cat|
                if not cat.subcats.blank?
                    cat.subcats.each do |child|
                        Healthcat.find(child.id).destroy
                    end
                end
                cat.destroy
            end
            redirect_to admin_healthcats_path
        elsif params[:move_button]
            Healthcat.find(params[:cats]).each do |cat|
                if not cat.subcats.blank?
                    cat.subcats.each do |child|
                        child.update_attributes(:parent_id => params[:parent_cat])
                    end
                end
                cat.update_attributes(:parent_id => params[:parent_cat])
            end
            redirect_to admin_healthcats_path
        end        
    end

    private
        def find_healthcat
            @healthcat = Healthcat.find(params[:id])
        end

        def bodyparts_list
            @bodyparts = Bodypart.order(:name).all
        end
end

app/controllers/healthcats_controller.rb
class HealthcatsController < ApplicationController
    load_and_authorize_resource

    before_filter :find_healthcat, :except => [:index, :new, :create]

    def index
        @healthcats = Healthcat.all_parents
    end

    def new
        @healthcat = Healthcat.new
    end

    def create
        @healthcat = Healthcat.new(params[:healthcat])
        if params[:cancel_button] || @healthcat.save
            redirect_to healthcats_path
        else
            render :new
        end
    end

    def edit
    end

    def update
        if params[:cancel_button] || @healthcat.update_attributes(params[:healthcat])
            redirect_to healthcats_path
        else
            render :edit
        end
    end

    def show
        @healthcat = Healthcat.find(params[:id])
        @children = @healthcat.subcats
        @categorizable = @healthcat
        @articles = @categorizable.articles.order(:name)
    end

    def destroy
        @children = @healthcat.subcats
        if not @children.blank?
            @children.each do |child|
                Healthcat.find(child.id).destroy
            end
        end
        @healthcat.destroy
        redirect_to healthcats_path
    end

    private
        def find_healthcat
            @healthcat = Healthcat.find(params[:id])
        end
end

app/helpers/healthcats_helper.rb
module HealthcatsHelper
end

app/views/admin/healthcats/_form.html.erb
<%= form_for([:admin, @healthcat], :html => {:class => "form-horizontal"}) do |f| %>
    <div class="control-group">
        <%= f.label :name, :class => "control-label" %>
        <div class="controls">
            <%= f.text_field :name, :autofocus => true, :class => "full_width" %>
        </div>
    </div>
    <div class="control-group">
        <%= f.label :description, :class => "control-label" %>
        <div class="controls">
            <%= f.text_area :description, :rows => 4, :class => "full_width" %>
        </div>
    </div>
    <div class="control-group">
        <%= f.label :parent_id, :class => "control-label" %>
        <div class="controls">
            <% if params[:parent] %>
                <%= f.collection_select :parent_id, Healthcat.all_parents, :id, :name, :include_blank => true, :selected => params[:parent] %>
            <% else %>
                <%= f.collection_select :parent_id, Healthcat.all_parents, :id, :name, :include_blank => true %>
            <% end %>
        </div>
    </div>
    <div class="control-group gender">
        <%= f.label :gender, :class => "control-label" %>
        <div class="controls">
            <%= f.select :gender, Healthcat.genders, :include_blank => true %>
        </div>
    </div>
    <div class="control-group">
        <%= f.label :bodyparts, :class => "control-label" %>
        <div class="controls">
            <%= f.text_field :bodypart_names %>
            <div class="parts"></div>
            <div class="dropdown add_by_click">
                <a class="dropdown-toggle" data-toggle="dropdown" id="add_parts" href="#"><%= t('shared.actions.add.simple') %></a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="add_parts">
                    <% @bodyparts.each do |part| %>
                        <li class="enable visible"><%= part.name %></li>
                    <% end %>
                    <li class="nothing_to_add"><%= t('shared.messages.nothing_to_add') %></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <%= f.submit t('shared.actions.save'), {:class => "btn-primary btn"} %>
            <%= submit_tag t('shared.actions.cancel'), {:name => 'cancel_button', :class => "btn"} %>
        </div>
    </div>
<% end %>

app/views/admin/healthcats/_healthcat.html.erb
<% if not @healthcat.description.blank? %>
    <div class="show_group">
        <div><%= @healthcat.description %></div>
    </div>
<% end %>
<% if not @child_healthcats.blank? %>
    <div class="show_group">
        <h5><%= t('shared.healthcat.childrens_list') %></h5>
        <ul class="subcats">
            <% @child_healthcats.each do |child| %>
                <li><%= link_to child.name, show_path( @healthcat.id, @healthcat.translated_name, child.id, child.translated_name) %></li>
            <% end %>
            <% if can? :create, :healthcat %>
                <li><%= link_to t('shared.healthcat.add_new'), { :controller => "healthcats", :action => "new", :parent => @healthcat.id } %></li>
            <% end %>
        </ul>
    </div>
<% else%>
    <% if can? :create, :healthcat %>
        <% if @healthcat.parent.blank? %>
            <ul class="subcats">
                <li><%= link_to t('shared.healthcat.add_new'), { :controller => "healthcats", :action => "new", :parent => @healthcat.id } %></li>
            </ul>
        <% end %>
    <% end %>
<% end %>

app/views/admin/healthcats/destroy.html.erb
<h1>Healthcats#destroy</h1>
<p>Find me in app/views/healthcats/destroy.html.erb</p>

app/views/admin/healthcats/edit.html.erb
<% content_for :title do %>
    <%= t('.title') %>
<% end %>

<div class="span12">
    <h2 class="form_title"><%= t('.title') %></h2>

    <%= render "form" %>
</div>

app/views/admin/healthcats/index.html.erb
<% content_for :title do %>
    <%= t('.title') %>
<% end %>

<%= form_tag('categories/move', :method => :post) do %>
    <table width="100%" class="fixed">
        <tbody>
            <tr class="header">
                <td><h3><%= t('healthcats.shared.categories') %></h3></td>
                <td class="right">
                    <%= link_to t('shared.actions.add.with_icon_html'), new_admin_healthcat_path, :class => "btn btn-primary" %>
                    <%= submit_tag t('shared.actions.delete.simple'), :name => 'delete_button', :class => "btn" %>
                    <%= submit_tag t('shared.actions.move'), :name => 'move_button', :class => "btn" %>
                    <%= select_tag :parent_cat, options_from_collection_for_select(Healthcat.all_parents, :id, :name) + "<option value=''>#{t('shared.move_to_root')}</option>".html_safe, :include_blank => true %>
                </td>
            </tr>
        </tbody>
    </table>

    <table width="100%" class="table">
        <tbody>
            <% if @healthcats.blank? %>
                <tr>
                    <td colspan="5"><%= t('shared.no_info') %></td>
                </tr>
            <% else %>
                <tr>
                    <th width="20px"><%= check_box_tag 'check_all' %></th>
                    <th><%= t('shared.name') %></th>
                    <th width="150px" class="center"><%= t('shared.articles_count') %></th>
                    <th width="110px"><%= t('shared.created_at') %></th>
                    <th width="20px"></th>
                </tr>
                <% @healthcats.each do |cat| %>
                    <tr>
                        <td><%= check_box_tag "cats[]", cat.id  %></td>
                        <td><%= link_to cat.name, edit_admin_healthcat_path(cat.id) %></td>
                        <td class="center"><%= cat.count_of_articles %></td>
                        <td class="small"><%= l cat.created_at.to_time, :format => :short_date %></td>
                        <% if not cat.subcats.blank? %>
                            <td class="display_subcats"><i class="icon-chevron-down pull-right"></i></td>
                        <% else %>
                            <td></td>
                        <% end %>
                    </tr>
                    <% if not cat.subcats.blank? %>
                        <tr class="subcat">
                            <td colspan="5">
                                <div class="slide_panel">
                                    <table width="100%" class="table">
                                        <tbody>
                                            <% cat.subcats.each do |child| %>
                                                <tr>
                                                    <td width="20px"><%= check_box_tag "cats[]", child.id  %></td>
                                                    <td class="child">&mdash;&nbsp;&nbsp;<%= link_to child.name, edit_admin_healthcat_path(child.id) %></td>
                                                    <td class="center" width="150px"><%= child.count_of_articles %></td>
                                                    <td width="110px" class="small"><%= l child.created_at.to_time, :format => :short_date %></td>
                                                    <td width="20px"></td>
                                                </tr>
                                            <% end %>
                                        </tbody>
                                    </table>
                                </div>
                            </td>
                        </tr>
                    <% end %>
                <% end %>
            <% end %>
        </tbody>
    </table>
<% end %>
<div class="pagination-centered">
    <%= paginate @healthcats %>
</div>

app/views/admin/healthcats/new.html.erb
<% content_for :title do %>
    <%= t('.title') %>
<% end %>

<div class="span12">
    <h2 class="form_title"><%= t('.title') %></h2>

    <%= render 'admin/healthcats/form' %>
</div>

app/views/admin/healthcats/show.html.erb
<% content_for :title do %>
    <%= @healthcat.name %>
<% end %>

<%= render "shared/breadcrumbs/breadcrumbs_health_list" %>

<div class="span12">
    <table>
        <tbody>
            <tr>
                <td><h2><%= @healthcat.name %></h2></td>
                <% if can? :update, :healthcat %>
                    <td class="modify">
                        <div class="control_panel">
                            <%= link_to t('shared.actions.edit'), edit_healthcat_path %>
                            <%= link_to t('shared.actions.delete'), @healthcat, :method => :delete if can? :destroy, :healthcat %>
                        </div>
                    </td>
                <% end %>
            </tr>
        </tbody>
    </table>
    <%= render "healthcat" %>
</div>