config/routes.rb
MedPort::Application.routes.draw do
  get "organizations/show"

    root :to => "pages#home"

    devise_for :users

    resources :users, :only => [ :show, :index ]
    resources :categories
    resources :healthcats, :path => "sprav/cats"  do
        resources :healthcats, :path => "/subcats", :as => :subcats do
            resources :articles, :only => [ :show, :index ]
        end
    end
    resources :articles
    resources :bodyparts
    resources :tags
    resources :organizations

    match "home" => "pages#home", :as => "home"
    match "parallax" => "pages#parallax", :as => "parallax" #remove (test parallax scrolling)
    match "sprav/articles" => "articles#health", :as => "health_articles"

    namespace :admin do
        match "home" => "pages#home", :as => "home"
        match "canvas" => "pages#canvas", :as => "canvas" #remove this path (canvas test page)

        resources :healthcats, :path => "zabolevaniya/categories" do
            collection do
                delete 'destroy'
                post 'move'
            end
        end
        resources :bodyparts do
            collection do
                delete 'destroy'
            end
        end
        resources :articles do
            collection do
                delete 'destroy'
            end
        end
        resources :tags do
            collection do
                delete 'destroy'
            end
        end
        resources :organizations do
            collection do
                delete 'destroy'
            end
        end
    end
end

app/models/article.rb
class Article < ActiveRecord::Base
    include Translator

    attr_accessible :body, :introduction, :name, :translated_name, :categorizable_id, :categorizable_type

    belongs_to :categorizable, :polymorphic => true
    has_many :taggings, :dependent => :destroy
    has_many :tags, :through => :taggings

    scope :all_healthcats, lambda { where('categorizable_type IS ?', "Healthcat").order(:name) }

    validates_presence_of :name, :body
    validates_uniqueness_of :name

    def to_param
        "#{id}-#{translated_name}"
    end

    def tag_names=(names)
        names_line = "".encode("cp1251") + names
        names_line = names_line.gsub(/^(; *)+/, "")
        self.tags = Tag.with_names(names_line.split(%r{; +}))
    end

    def tag_names
        tags.map(&:name).join('; ')
    end

    before_save :set_translate_name

    private
        def set_translate_name
            self.translated_name = translate(self.name)
        end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
    before_filter :check_authorized
    before_filter :find_categorizable, :only => [ :create, :update ]

    load_and_authorize_resource

    layout "dashboard"

    def index
        if params[:cats].eql?("healthcats")
            @articles = Article.healthcats.order(:name)
        end
    end

    def new
        @article = Article.new
    end

    def create
        @article = @categorizable.articles.new(params[:article])
        if params[:cancel_button] || @article.save
            redirect_to admin_articles_path
        else
            render :new
        end
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = @categorizable.articles.find(params[:id])
        if params[:cancel_button] || @article.update_attributes(params[:article])
            redirect_to :controller => 'admin/articles', :action => 'index'
        else
            render :edit
        end
    end

    def show
        @article = Article.find(params[:id])
    end

    def destroy
        Article.find(params[:articles]).each { |article| article.destroy}
        redirect_to admin_articles_path
    end

    private
        def find_categorizable
            if params[:article]["categorizable_type"].blank?
                @klass = params[:categorizable_type].capitalize.constantize 
            else
                @klass = params[:article]["categorizable_type"].constantize
            end
            @categorizable = @klass.find(params[:article]["categorizable_id"])
		end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    load_and_authorize_resource

    before_filter :find_categorizable, :except => [ :index, :health, :show ]

    def index
        @articles = Article.all
    end

    def health
        @groups = Article.all_healthcats.group_by { |article| article.name[0] }
    end

    def new
        @article = Article.new
    end

    def create
        @article = @categorizable.articles.new(params[:article])
        if params[:cancel_button] || @article.save
            respond_to do |format|
                format.html { redirect_to healthcat_subcat_path( @article.categorizable.parent, @article.categorizable ) }
            end
        else
            render :new
        end
    end

    def edit
        @article = @categorizable.articles.find(params[:id])
    end

    def update
        @article = @categorizable.articles.find(params[:id])
        @article.update_attributes(params[:article])
        redirect_to healthcats_path
    end

    def show
        @article = Article.find(params[:id])
    end

    def destroy
        @article = @categorizable.articles.find(params[:id])
        @article.destroy
        redirect_to root_path
    end

    private
        def find_article
            @article = @categorizable.articles.find(params[:id])
        end

        def find_categorizable
            @klass = params[:categorizable_type].capitalize.constantize
            @categorizable = @klass.find(params[:categorizable_id])
		end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article, :html => {:class => "form-horizontal"}) do |f| %>
    <div class="control-group">
        <%= f.label :name, :class => "control-label" %>
        <div class="controls">
            <%= f.text_field :name, :autofocus => true, :class => "full_width" %>
        </div>
    </div>
    <ul class="nav nav-tabs" id="article_healthcats_tabs">
        <li><a href="#show"><%= t('shared.actions.show') %></a></li>
        <li><a href="#edit"><%= t('shared.actions.edit') %></a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane" id="show">
            <div class="full_width" id="show_article_intro">
                    <%= @article.introduction.html_safe if not @article.introduction.blank? %>
            </div>
            <div class="full_width" id="show_article_body">
                <%= @article.body.html_safe if not @article.body.blank? %>
            </div>
        </div>
        <div class="tab-pane" id="edit">
            <div class="control-group">
                <%= f.label :introduction, :class => "control-label" %>
                <div class="controls">
                    <%= f.text_area :introduction, :rows => 4, :class => "full_width" %>
                </div>
            </div>
            <div class="control-group">
                <%= f.label :body, :class => "control-label" %>
                <div class="controls">
                    <%= f.text_area :body, :rows => 14, :class => "full_width" %>
                </div>
            </div>
        </div>
    </div>
    <%= hidden_field_tag 'categorizable_type', 'healthcat' %>
    <%= hidden_field_tag 'categorizable_id', @categorizable.id %>
    <div class="control-group">
        <div class="controls">
            <%= f.submit t('shared.actions.save'), {:class => "btn-primary btn"} %>
            <%= submit_tag t('shared.actions.cancel'), {:name => 'cancel_button', :class => "btn"} %>
        </div>
    </div>
<% end %>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<% content_for :title do %>
    <%= t('.title') %>
<% end %>

<div class="span12">
    <h2 class="form_title"><%= t('.title') %></h2>

    <%= render 'form' %>
</div>

app/views/articles/health.html.erb
<% content_for :title do %>
    <%= t('.title') %>
<% end %>

<%= render 'shared/healthcats/title_menu' %>

<div class="container-fluid">
    <ul class="nav nav-pills">
        <% @groups.each_key do |letter| %>
            <li><a href="#<%= letter %>"><%= letter %></a></li>
        <% end %>
    </ul>
</div>
<div class="container-fluid">
    <% if @articles.blank? %>
        <p><%= t('shared.no_info') %></p>
    <% else %>
        <% @groups.each_pair do |letter, group| %>
            <h3><a class="anchor" name="<%= letter %>"><%= letter %></a></h3>
            <ul class="unstyled">
                <% group.each do |article| %>
                    <li>
                        <%= link_to article.name, healthcat_subcat_article_path(article.categorizable.parent, article.categorizable, article) %>
                        <span class="label label-info label_health"><%= link_to article.categorizable.parent.name, healthcat_subcat_path(article.categorizable.parent, article.categorizable) %></span>
                    </li>
                <% end %>
            </ul>
        <% end %>
    <% end %>
</div>

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>

app/views/articles/new.html.erb
<% content_for :title do %>
    <%= t('.title') %>
<% end %>

<div class="span12">
    <h2 class="form_title"><%= t('.title') %></h2>

    <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<% content_for :title do %>
    <%= @article.name %>
<% end %>

<%= render "shared/breadcrumbs/breadcrumbs_article" %>

<h1><%= @article.name %></h1>
<div><%= raw @article.introduction if not @article.introduction.blank? %></div>
<div><%= raw @article.body if not @article.body.blank? %></div>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>