config/routes.rb
MedPort::Application.routes.draw do
  get "organizations/show"

    root :to => "pages#home"

    devise_for :users

    resources :users, :only => [ :show, :index ]
    resources :categories
    resources :healthcats, :path => "sprav/cats"  do
        resources :healthcats, :path => "/subcats", :as => :subcats do
            resources :articles, :only => [ :show, :index ]
        end
    end
    resources :articles
    resources :bodyparts
    resources :tags
    resources :organizations

    match "home" => "pages#home", :as => "home"
    match "parallax" => "pages#parallax", :as => "parallax" #remove (test parallax scrolling)
    match "sprav/articles" => "articles#health", :as => "health_articles"

    namespace :admin do
        match "home" => "pages#home", :as => "home"
        match "canvas" => "pages#canvas", :as => "canvas" #remove this path (canvas test page)

        resources :healthcats, :path => "zabolevaniya/categories" do
            collection do
                delete 'destroy'
                post 'move'
            end
        end
        resources :bodyparts do
            collection do
                delete 'destroy'
            end
        end
        resources :articles do
            collection do
                delete 'destroy'
            end
        end
        resources :tags do
            collection do
                delete 'destroy'
            end
        end
        resources :organizations do
            collection do
                delete 'destroy'
            end
        end
    end
end

app/models/ability.rb
class Ability
    include CanCan::Ability

    def initialize(user)
        can :read, :all
        can :health, Article

        if user.try(:admin?)
            can :manage, :all
        end
    end
end

app/models/article.rb
class Article < ActiveRecord::Base
    include Translator

    attr_accessible :body, :introduction, :name, :translated_name, :categorizable_id, :categorizable_type

    belongs_to :categorizable, :polymorphic => true
    has_many :taggings, :dependent => :destroy
    has_many :tags, :through => :taggings

    scope :all_healthcats, lambda { where('categorizable_type IS ?', "Healthcat").order(:name) }

    validates_presence_of :name, :body
    validates_uniqueness_of :name

    def to_param
        "#{id}-#{translated_name}"
    end

    def tag_names=(names)
        names_line = "".encode("cp1251") + names
        names_line = names_line.gsub(/^(; *)+/, "")
        self.tags = Tag.with_names(names_line.split(%r{; +}))
    end

    def tag_names
        tags.map(&:name).join('; ')
    end

    before_save :set_translate_name

    private
        def set_translate_name
            self.translated_name = translate(self.name)
        end
end

app/models/bodypart.rb
class Bodypart < ActiveRecord::Base
    attr_accessible :name

    has_many :placings, :dependent => :destroy
    has_many :healthcats, :through => :placings

    validates_presence_of :name
    validates_uniqueness_of :name

    def self.with_names(names)
        names.map do |name|
            Bodypart.find_by_name(name)
        end
    end
end

app/models/category.rb
class Category < ActiveRecord::Base
    attr_accessible :description, :name

    validates_presence_of :name
end

app/models/healthcat.rb
class Healthcat < ActiveRecord::Base
    include Translator

    attr_accessible :name, :translated_name, :description, :parent_id, :gender, :bodypart_names

    cattr_accessor :genders do
        [ [ I18n.t('shared.genders.male'), "male" ], [ I18n.t('shared.genders.female'), "female" ] ]
    end

    has_many :subcats, :class_name => "Healthcat", :foreign_key => "parent_id"
    belongs_to :parent, :class_name => "Healthcat", :foreign_key => "parent_id"
    has_many :placings, :dependent => :destroy
    has_many :bodyparts, :through => :placings
    has_many :articles, :as => :categorizable

    scope :all_parents, lambda { where('parent_id IS ?', nil).order(:name) }

    validates_presence_of :name

    def count_of_articles
        count = 0
        if not self.subcats.blank?
            self.subcats.each do |child|
                count = count + child.articles.count if not child.articles.blank?
            end
        else
            count = self.articles.count if not self.articles.blank?
        end
        return count
    end

    def to_param
        "#{id}-#{translated_name}"
    end

    def bodypart_names=(names)
        names_line = "".encode("cp1251") + names
        names_line = names_line.gsub(/^(, *)+/, "")
        self.bodyparts = Bodypart.with_names(names_line.split(%r{, +}))
    end

    def bodypart_names
        bodyparts.map(&:name).join(', ')
    end

    before_save :set_childs_gender, :set_translate_name

    private
        def set_childs_gender
            self.gender = self.parent.gender if not self.parent_id.blank?
        end

        def set_translate_name
            self.translated_name = translate(self.name)
        end
end

app/models/organization.rb
class Organization < ActiveRecord::Base
    attr_accessible :address, :description, :name

    validates_presence_of :name, :address
end

app/models/placing.rb
class Placing < ActiveRecord::Base
    belongs_to :healthcat
    belongs_to :bodypart
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    attr_accessible :name

    has_many :taggings, :dependent => :destroy
    has_many :articles, :through => :taggings

    validates_presence_of :name
    validates_uniqueness_of :name

    def self.with_names(names)
        names.map do |name|
            Tag.find_or_create_by_name(name)
        end
    end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
    belongs_to :article
    belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :token_authenticatable, :confirmable,
    # :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable, :confirmable,
           :recoverable, :rememberable, :trackable, :validatable

    # Setup accessible (or protected) attributes for your model
    attr_accessible :email, :password, :password_confirmation, :remember_me
    # attr_accessible :title, :body

    before_validation :confirm

    private
        def confirm
            self.password_confirmation = self.password
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def parallax
        render :layout => false
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bodyparts_helper.rb
module BodypartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-error">
      <h4>#{sentence}</h4>
      <ul class="unstyled">#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/healthcats_helper.rb
module HealthcatsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/admin/pages/canvas.html.erb
<div id="canvasDiv"></div>
<button id="clear" class="btn btn-warning" type="button">Clear canvas</button>
<button id="close_path" class="btn btn-primary" type="button">Close path</button>

app/views/admin/pages/home.html.erb
<% content_for :title do %>
    <%= t('.title') %>
<% end %>

app/views/shared/_header.html.erb
<h1><%= link_to t('shared.title'), root_path, { :class => "no_link"  } %></h1>

app/views/shared/_top_nav.html.erb
<div class="navbar">
    <div class="navbar-inner">
        <ul class="nav">
            <% if user_signed_in? %>
                <li><%= link_to t('devise.actions.logout'), destroy_user_session_path, :method => :get %></li>
                <li><%= link_to t('devise.actions.edit_account'), edit_user_registration_path %></li>
                <% if current_user.try(:admin?) %>
                    <li><%= link_to t('devise.actions.admin_panel'), admin_home_path %></li>
                <% end %>
            <% else %>
                <li><%= link_to t('devise.actions.login'), new_user_session_path %></li>
                <li><%= link_to t('devise.actions.sign_up'), new_user_registration_path %></li>
            <% end %>
        </ul>
    </div>
</div>

app/views/shared/headers/_health_list.html.erb
<div class="span12">
    <div class="row">
        <div class="span6">
            <h2><%= t('health_list.title') %></h2>
        </div>
        <div class="cats_tabs span6">
            <ul class="nav nav-pills pull-right">
                <%= content_tag :li, :class => ('active' if params[:controller] == "healthcats" && params[:action] == "index") do %>
                    <%= link_to t('health_list.categories'), healthcats_path %></li>
                <% end %>
                <%= content_tag :li, :class => ('active' if params[:controller] == "articles" && params[:action] == "index") do %>
                    <%= link_to t('health_list.abc'), articles_path %></li>
                <% end %>
                <%= content_tag :li, :class => ('active' if params[:controller] == "tags" && params[:action] == "index") do %>
                    <%= link_to t('health_list.tags') %></li>
                <% end %>
            </ul>
        </div>
    </div>
</div>

app/views/shared/headers/_spravochnik.html.erb
<div class="span12">
    <div class="row">
        <div class="span6">
            <h2><%= t('spravochnik.title') %></h2>
        </div>
        <div class="cats_tabs span6">
            <ul class="nav nav-pills pull-right">
                <%= content_tag :li, :class => ('active' if params[:controller] == "healthcats" && params[:action] == "index") do %>
                    <%= link_to t('spravochnik.categories'), healthcats_path %></li>
                <% end %>
                <%= content_tag :li, :class => ('active' if params[:controller] == "articles" && params[:action] == "index") do %>
                    <%= link_to t('spravochnik.abc') %></li>
                <% end %>
                <%= content_tag :li, :class => ('active' if params[:controller] == "tags" && params[:action] == "index") do %>
                    <%= link_to t('spravochnik.tags') %></li>
                <% end %>
            </ul>
        </div>
    </div>
</div>